#ifndef CONFIG_H
#define CONFIG_H
#define WIDTH 1440
#define HEIGHT 810
#define PATH  "./GM.rcc"
#define GRAVITY 1
#define VY0 -9
#define FPS 16
#define ROLE_WIDTH 112
#define ROLE_HEIGHT 98
#define ROLE_PATH ":/res/role-%1.png"
#define ROLE_STOP_PATH ":/res/role-stop.png"
#define ROLE_MAX 10
#define ROLE_V 2
#define CUBE_PATH ":/res/cube.jpg"
#define CUBE_L 20
#define GUN_WIDTH 88
#define GUN_HEIGHT 48
#define GUN_PATH ":/res/gun-1.png"
#define BULLET_PATH ":/res/bullet-%1.png"
#define BULLET_L 24
#define BOMB_PATH ":/res/bomb.png"
#define BOMB_WIDTH 96
#define BOMB_HEIGHT 64
#define BOMB_LAST 16
#define pii std::pair<int,int>
#define PI 3.1415926
#define BUTTON_PATH ":/res/button.png"
#define BUTTON_FILE "/button.txt"
#define EXIT_PATH ":/res/exit.png"
#define ELEM_FILE "/elementary.txt"
#define STATEMENT "使用A、D移动您的人物，W、S转动您的枪械，J发射子弹，K跳跃\n子弹碰到墙壁将反弹，子弹可以消灭目标或触发机关\n现在，用您学的东西去挑战关卡吧！"
#define SAVEDATA_PATH "savedata.txt"
#define MAP_FILE "/map.txt"
#define MONSTER1_PATH ":/res/monster-1.png"
#define MONSTER1_WIDTH 92
#define MONSTER1_HEIGHT 82
#define MONSTER1_FILE "/monster1.txt"
#define MONSTER2_PATH ":/res/monster-2.png"
#define MONSTER2_FILE "/monster2.txt"
#define MONSTER2_WIDTH 68
#define MONSTER2_HEIGHT 70
#define MONSTER2_FRONT 23
#define MONSTER2_HEIGHT2 47
#define MONSTER3_PATH ":/res/monster-3.png"
#define MONSTER3_WIDTH 36
#define MONSTER3_HEIGHT 18
#define MONSTER3_FILE "/monster3.txt"
#define BACKGROUND_PATH ":/res/background.jpg"
#define BACKGROUND2_PATH ":/res/background2.jpg"
#endif // CONFIG_H
